name: Close PR on Open

on:
  pull_request:
    types: [opened]

jobs:
  close_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Close the PR with a comment
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "This PR is being closed automatically."
        gh pr close ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
        GH_TOKEN: ${{ secrets.REPO_ACCESS }}
