name: Close PR if not from main branch

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - release

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Check if PR is from main branch
        id: check_branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == "main" ]]; then
            echo "is_main=true" >> $GITHUB_ENV
          else
            echo "is_main=false" >> $GITHUB_ENV
          fi

      - name: Close Pull Request if not from main
        if: env.is_main != 'true'
        run: |
          pr_number=${{ github.event.pull_request.number }}
          gh pr close $pr_number --comment "This pull request is not from the main branch and has been automatically closed. Please review the branch management policy: [Link to document]."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
