name: Close PR if not from main branch

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  close-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Close Pull
      run: gh pr close --comment "Auto-closing pull request"
      env:
        GH_TOKEN: ${{ secrets.REPO_ACCESS }}
