name: Check PR Branch

on:
  pull_request:
    branches:
      - release

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from main branch
        id: check_branch
        run: echo ::set-output name=is_main::$(echo "${{ github.event.pull_request.base.ref }}" == "main")

      - name: Close PR if not from main branch
        if: steps.check_branch.outputs.is_main != 'true'
        run: |
          echo "This pull request is not from the main branch and cannot be merged into the release branch. Please review the branch management policy: [Link to document]."
          echo "Closing the pull request..."
          gh pr close ${GITHUB_REF}
          echo "Adding comment to the pull request..."
          gh pr comment ${GITHUB_REF} --body "This pull request is not from the main branch and has been automatically closed. Please review the branch management policy: [Link to document]."
