name: Close PR on Open

on:
  pull_request:
    types: [opened]
    # branches:
    #   - release

jobs:
  close_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Close the PR with a comment
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "This pull request is not from the main branch and has been automatically closed. Please review the branch management policy."
        gh pr close ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS }}
        GH_TOKEN: ${{ secrets.REPO_ACCESS }}
