name: Check Version

on:
  pull_request:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get latest release tag
        id: get_latest_release
        uses: actions/github-script@v3
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return latestRelease.data.tag_name;

      - name: Check if version is higher
        id: check_version
        run: |
          LATEST_RELEASE=${{ steps.get_latest_release.outputs.result }}
          CURRENT_VERSION=${{ env.VERSION }}

          if [ "$(printf '%s\n' "$LATEST_RELEASE" "$CURRENT_VERSION" | sort -V | head -n1)" = "$CURRENT_VERSION" ]; then
            echo "Error: Current version ($CURRENT_VERSION) is not greater than the latest release version ($LATEST_RELEASE)."
            exit 1
          else
            echo "Current version ($CURRENT_VERSION) is greater than the latest release version ($LATEST_RELEASE)."
          fi
