name: Update Manifest Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: echo "::set-output name=current_version::$(jq -r '.version' public/manifest.json)"

      - name: Increment version
        id: increment_version
        run: |
          current_version="${{ steps.get_version.outputs.current_version }}"
          major=$(echo $current_version | cut -d'.' -f1)
          minor=$(echo $current_version | cut -d'.' -f2)
          patch=$(echo $current_version | cut -d'.' -f3)
          next_version="$((major + 1)).0.0"
          echo "::set-output name=next_version::$next_version"

      - name: Update manifest version
        run: |
          next_version="${{ steps.increment_version.outputs.next_version }}"
          jq --arg new_version "$next_version" '.version = $new_version' public/manifest.json > tmp_manifest.json
          mv tmp_manifest.json public/manifest.json

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Bump up manifest version to ${{ steps.increment_version.outputs.next_version }}"
          add: "public/manifest.json"
          force: true
          push: true
