name: create_release

on:
  push:
    branches:
      - main
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(node -p 'require("./public/manifest.json").version')"
      - name: Create release zip
        run: zip -r build.zip build/*
      - name: Rename ZIP file
        run: |
          mv build.zip extension-${{ steps.version.outputs.version }}.zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-zip
          path: extension-${{ steps.version.outputs.version }}.zip
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: "Changelog: https://github.com/${{ github.repository }}/commits/${{ steps.version.outputs.version }}"
          tag: ${{ steps.version.outputs.version }}
          token: ${{ secrets.REPO_ACCESS }}
          artifacts: extension-${{ steps.version.outputs.version }}.zip
          allowUpdates: true
          replacesArtifacts: true
