name: Modify Version

on:
  push:
    branches:
      - main

jobs:
  modify_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Current Version
        id: get_version
        run: |
          current_version=$(jq -r '.version' public/manifest.json)
          echo "::set-output name=version::$current_version"

      - name: Increment Version
        id: increment_version
        run: |
          major=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. '{print $1}')
          minor=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. '{print $2}')
          patch=$(echo "${{ steps.get_version.outputs.version }}" | awk -F. '{print $3}')
          new_version="$major.$minor.$((patch+1))"
          echo "::set-output name=version::$new_version"

      - name: Update Version
        run: |
          sed -i 's/"version": "${{ steps.get_version.outputs.version }}"/"version": "${{ steps.increment_version.outputs.version }}"/' public/manifest.json
