name: Bump version on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@v10.0.1
      env:
        GITHUB_TOKEN: "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"
      with:
        path: 'public'
        filename: 'manifest.json'
