name: create_release

on:
  push:
    branches:
      - main
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'public/manifest.json'
          prop_path: 'version'
      - name: Create release zip
        run: |
          cd build
          zip -r ../extension-${{ steps.version.outputs.prop }}.zip .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-zip
          path: extension-${{ steps.version.outputs.prop }}.zip
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: "Changelog: https://github.com/${{ github.repository }}/commits/${{ steps.version.outputs.prop }}"
          tag: ${{ steps.version.outputs.prop }}
          token: ${{ secrets.REPO_ACCESS }}
          artifacts: extension-${{ steps.version.outputs.prop }}.zip
          allowUpdates: true
          replacesArtifacts: true
