name: create_release

on:
  push:
    branches:
      - main
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Choisissez la version de Node.js que vous souhaitez utiliser
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(node -p 'require("./build/manifest.json").version')"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          body: "Changelog: https://github.com/${{ github.repository }}/commits/${{ steps.version.outputs.prop }}"
          tag: ${{ steps.version.outputs.prop }}
          token: "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"
          artifacts: build/
          allowUpdates: true
          replacesArtifacts: true
