name: Version Check

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - main

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: |
          NEW_VERSION=$(node -p -e "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Get latest release version
        id: get_latest_release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Check version
        run: |
          echo "New version: $NEW_VERSION"
          echo "Latest release version: $LATEST_VERSION"
          if [ "$(printf '%s\n' "$NEW_VERSION" "$LATEST_VERSION" | sort -V | head -n1)" = "$NEW_VERSION" ]; then
            echo "Error: New version ($NEW_VERSION) is not greater than the latest release version ($LATEST_VERSION)."
            exit 1
          fi
